services:

  sing-box:
          image: ghcr.io/sagernet/sing-box:v1.13.5
    container_name: sing-box
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    command:
      - -D
      - /var/lib/sing-box
      - -C
      - /etc/sing-box/
      - run
    volumes:
      - ./sing-box/config.json:/etc/sing-box/config.json:ro
      - ./sing-box/data:/var/lib/sing-box
      - ./sing-box/tls:/etc/sing-box/tls:ro
    restart: unless-stopped
