---
deploy_dir: /root/wormhole
local_dir: '{{ playbook_dir }}/local/{{ inventory_dir | basename }}'
tcp_congestion_control: 'bbr'
vpn_subnet_pool: '10.0.0.0/8'
vpn_subnet_prefix: 24
vpn_reserved_cidrs: []
awg:
  port: 51820
wg:
  port: 51822
vless:
  port: 443
  handshake_port: 443
  domain: 'www.cloudflare.com'
  max_time_difference: '1m'
  client_fingerprint: 'chrome'
  grpc_service_name: 'api.v1.Gateway'
