---
deploy_dir: /root/wormhole
tcp_congestion_control: 'bbr'
awg:
  port: 51820
wg:
  port: 51822
vless:
  port: 443
  domain: 'www.cloudflare.com'
  max_time_difference: '1m'
  client_fingerprint: 'chrome'
